### ISSUE TITLE
Excel format / Offset is accidentally incremented, if not explicitly set

### ISSUE THREAD

**Issue by Fannon** [SemanticMediaWiki/SemanticResultFormats#171]
Hello!

It took me a while to reproduce this, but the excel format seems to be broken. In many cases it returned no result rows (just the header), or some results were missing. 

This seems to be caused by the generated the link to the actual file download:
```php
$this->getLink( $res, $outputMode )->getText( $outputMode, $this->mLinker );
```

When no offset is explicitly set, it will increse the offset for every result row the query returned when generating the link. 

E.g. this query has a limit of 5 items and no explicit offset
```
{{#ask:
  [[Category:Person]] 
  |?Modification date
  |format=excel
  |searchlabel=Download Excel
  |limit=5
}}
```

It generated the following link:

> /Special:Ask/-5B-5BCategory:Person-5D-5D/-3FModification-20date%3DModification-20Date/mainlabel%3D/limit%3D5/**offset%3D5**/format%3Dexcel/searchlabel%3DDownload-20Excel

The link now contains an offset parameter which is set to 5.

If I explicitly set the offset to 0, the excel format works as expected:
```
{{#ask:
  [[Category:Person]] 
  |?Modification date
  |format=excel
  |searchlabel=Download Excel
  |limit=5
  |offset=0
}}
```

I couln't find the real cause of this bug. I noticed that the CSV result format didn't have this issue, which is strange as it is working in a very similar fashion.

Best,
Simon

**Comment by kghbln** [comment]
@Fannon Thanks for reporting.
@netbrain Since you were the original author of this format you will probably like to have a peep at this and provide a fix. I believe this will be very much appreciated.

**Comment by netbrain** [comment]
@kghbln Sorry, but I don't have the time to look into this. And it's been several years since I last worked against this project so the current maintainer would probably have a better chance of getting this fixed.

**Comment by Fannon** [comment]
@netbrain I understand - thanks for writing this result format in the first place, it's very useful!

I did try to find and fix the bug myself, but it seems to be caused by some side-effect. My SMW / SRF development knowledge is a bit to shallow to find it easily.

**Comment by s7eph4n** [comment]
Could be that I fixed this already. Could you try the latest dev version?

**Comment by kghbln** [comment]
@Fannon Any news on this?

**Comment by kghbln** [comment]
So it believe this is fixed, due to the lack of feedback. In case it is still an issue this one may be reopened.

**Comment by Fannon** [comment]
Sorry for not responding, was away / busy for a while! 
Yes, let's close it. If its still broken and I can confirm it, I'll reopen this issue.
